### PR TITLE
remove exit plugin image_image for scratch build

### PR DESCRIPTION
**Pull request by rcerven**
Signed-off-by: Robert Cerven <rcerven@redhat.com>

### CODE REVIEW

**Comment by lkolacek** [comment]
:+1:

**Comment by twaugh** [comment]
Can we also update tests/build_/test_arrangements.py so that arrangement 5 includes import_image in both the postbuild and exit phases (since valid version-5 arrangements can have it in either)?

That should catch this.

**Comment by rcerven** [comment]
ok will update that test

**Comment by lcarva** [comment]
Not updating release notes draft because this is bugfix to an unreleased feature.

**Pull request merged**
