### PR TITLE
Allow setting secret for pulp_sync in sourceSecret

### PR DESCRIPTION
**Pull request by mmilata**
Whenever OpenShift < 1.0.6 is used.

This is osbs counterpart of projectatomic/atomic-reactor#370.

### CODE REVIEW

**Comment by twaugh** [comment]
I think we should probably verify that `sourceSecret` is not already set to some other value otherwise we'll overwrite `pulp_push`'s secret with `pulp_sync`'s if they are different. If they are different but we have to use `sourceSecret`, we should raise `OsbsValidationException` because we can't support more than one secret that way.

**Comment by twaugh** [comment]
...and now I remember that they can't have different secrets unless https://github.com/projectatomic/osbs-client/pull/293 is merged, which it probably won't be.

So LGTM :-)

**Comment by mmilata** [comment]
It won't hurt to add the check, just in case.

**Comment by twaugh** [comment]
LGTM, merging.

**Pull request merged**
