### PR TITLE
improve deployment guide

### LINKED ISSUE #157: improve deployment guide
Answer @maxamillion questions from rel-eng of fedora:

 - [x] Does OSBS need a Project inside of OpenShift?
 - [x] What kind of access to OpenShift does the OSBS builder need?
 - [x] Can OSBS share an OpenShift environment with other projects/users?
 - [x] document setup with htpasswd and username/password
 - [x] How to configure the above

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes #157 

CC @maxamillion

@mmilata could you please take a look?

### CODE REVIEW

**Comment by maxamillion** [comment]
+1 - This is great, thank you.

Also, if I may request improvement on the section about `dock` since that is now `atomic-reactor` and I feel as though there are some small details of how to actually get/import/build the builder image and then actually use it against an existing OpenShift environment.

Thank you!

**Comment by TomasTomecek** [comment]
You were quite right. The reactor section was really outdated. Should be fixed now.

**Comment by maxamillion** [comment]
+1 - looks great, thanks!

**Comment by TomasTomecek** [comment]
cleaning up commits is not really my thing;

ready for merge

**Comment by twaugh** [comment]
Looks great.

**Pull request merged**
