### PR TITLE
branch name is always required

### PR DESCRIPTION
**Pull request by rcerven**
Signed-off-by: Robert Cerven <rcerven@redhat.com>

### CODE REVIEW

**Comment by vrutkovs** [comment]
`create_prod_build` mentions `:param git_branch: str, branch name (may be None)`

**Comment by vrutkovs** [comment]
Also a lot of `kwargs.setdefault('git_branch', None)`

**Comment by lcarva** [comment]
> Also a lot of kwargs.setdefault('git_branch', None)

In addition, should probably adjust here too:
```python
osbs/build/build_request.py-        if self.spec.git_branch.value:
osbs/build/build_request.py:            self.set_label('git-branch', self.spec.git_branch.value)
osbs/build/build_request.py-        else:
osbs/build/build_request.py:            self.set_label('git-branch', 'unknown')
```

**Comment by lcarva** [comment]
This looks good, but let's hold off on merging until we can verify that our users have a heads up about this change.

**Comment by twaugh** [comment]
Will Fedora tooling need changes or does it already provide the git branch?

**Comment by lcarva** [comment]
> Will Fedora tooling need changes or does it already provide the git branch?

The fix was in pyrpkg which is used by fedpkg.

**Pull request merged**
