### PR TITLE
[spec] python macros

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
does this mean that we'll lose `/usr/bin/osbs`?

**Comment by jpopelka** [comment]
No,
`ln -s  %{_bindir}/osbs-%{binaries_py_version} %{buildroot}%{_bindir}/osbs`
means that `/usr/bin/osbs` will be a symlink to `/usr/bin/osbs-2.x` (rhel) or `/usr/bin/osbs-3.x` (Fedora)

**Comment by TomasTomecek** [comment]
/me is blind
LGTM

**Comment by TomasTomecek** [comment]
just want to double check: will this work in rhel 6 buildroots, right?

**Comment by jpopelka** [comment]
Yes:  https://brewweb.devel.redhat.com/taskinfo?taskID=10199290

**Comment by TomasTomecek** [comment]
Thanks!

**Pull request merged**
