### PR TITLE
Make setting architecture label optional

### LINKED ISSUE #159: make setting architecture optional
since reactor is able to inherit labels from base image, we don't need to force users of osbs-client to set the architecture value

### PR DESCRIPTION
**Pull request by mmilata**
Closes #159.

Depends on #266.

### CODE REVIEW

**Comment by jpopelka** [comment]
LGTM

**Comment by TomasTomecek** [comment]
This should be almost ready to get merged, right?

**Comment by mmilata** [comment]
Yup, forgot about this one. Rebased & ready for merge.

**Comment by jpopelka** [comment]
LGTM, merging

**Pull request merged**
