### PR TITLE
Strip log lines of trailing spaces only - this breaks exception traceback formatting

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by twaugh** [comment]
@jarodwilson, is removing this strip() a problem? https://github.com/projectatomic/osbs-client/pull/665#discussion_r132914664

**Comment by twaugh** [comment]
Would be nice to include a test for this.

**Comment by vrutkovs** [comment]
Will do, I'm thinking `rstrip()` would be a better solution, although I haven't seen extra newline chars yet

**Comment by jarodwilson** [comment]
If I'm remembering correctly, not having the strip there caused some minor formatting oddness with self-tests, but I think they could be adjusted slightly to compensate if that strip is really only useful for the self-test.

**Comment by jarodwilson** [comment]
Okay, never mind, the .strip() seems to be entirely superfluous now. I recall it being needed for self-tests for some iteration of this code, but it seems to not be now, so yeah, have at it, remove it entirely!

**Comment by lcarva** [comment]
Not updating release notes. This is a bugfix to unreleased changes.

**Pull request merged**
