### PR TITLE
Configure koji_promote plugin

### PR DESCRIPTION
**Pull request by twaugh**
Depends on https://github.com/projectatomic/atomic-reactor/pull/319.

### CODE REVIEW

**Comment by twaugh** [comment]
Ready for review.

**Comment by TomasTomecek** [comment]
LGTM

**Comment by mmilata** [comment]
LGTM but there's a merge conflict and my attempt to resolve it resulted in failing tests. Can you please rebase?

**Comment by twaugh** [comment]
Re-based.

**Comment by mmilata** [comment]
And merged.

**Comment by twaugh** [comment]
Thanks! Not sure why we didn't get a Travis CI/coveralls report.

**Pull request merged**
