### PR TITLE
Flatpak config cleanups

### PR DESCRIPTION
**Pull request by owtaylor**
Couple of tiny cleanups as a result of https://github.com/projectatomic/atomic-reactor/pull/1064 and https://github.com/projectatomic/atomic-reactor/pull/1065.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Looks good to me, but I'm not sure if the Travis failure is bogus or not.

**Comment by owtaylor** [comment]
Travis failure is https://pypi.org/project/py releasing a new version (1.6.0) a couple of days ago that drops python-2.6 support. test.sh could probably force downgrade that to the previous release with the right pip incantations - if centos 6 is still needed in the test matrix.

**Comment by lcarva** [comment]
Please rebase to pick up unit test fix.

**Comment by lcarva** [comment]
Updated release notes draft:
> - Flatpak base image can be set from reactor config map

**Pull request merged**
