### PR TITLE
docs: update deployment guide

### PR DESCRIPTION
**Pull request by TomasTomecek**
@pbabinca since you wrote the NFS part, I would like to author the commit on your behalf, would you mind that?

### CODE REVIEW

**Comment by pbabinca** [comment]
NFS part looks like my docs. Feel free to commit it in my name.

**Comment by twaugh** [comment]
How does this PR relate to #157?

**Comment by TomasTomecek** [comment]
not at all actually, I just wanted to open source our internal docs; that's what this PR is about

**Comment by TomasTomecek** [comment]
Merging this into #158

**Pull request closed without merging**
