### PR TITLE
Fix typo in conf method call

### PR DESCRIPTION
**Pull request by bkabrda**

### CODE REVIEW

**Comment by twaugh** [comment]
@bkabrda Mind if I add a test-case for that?

**Comment by bkabrda** [comment]
@twaugh please do! I'm really trying to get the imagestream story done today, so I just wanted to have a quick fix for this to be able to test my work.

**Comment by twaugh** [comment]
Wonder why @landscape-bot didn't spot it.

**Comment by twaugh** [comment]
...for one thing, it wasn't enabled for this repo. I've tried adding it now.

**Pull request merged**
