### PR TITLE
[WIP] Rewrite mock_jsons.sh in python

### LINKED ISSUE #79: rewrite mock_jsons.sh to python and use `osbs.http`
related #77

### PR DESCRIPTION
**Pull request by vrutkovs**
Fixes #79, however I don't know how do I test it

### CODE REVIEW

**Comment by TomasTomecek** [comment]
I think we should update versions to something recent. `0.x` is pretty old.

I would test it by running the script, saving jsons and running tests :)

**Comment by vrutkovs** [comment]
Oops, missed the requirement for ```osbs.http``` use here, lets mark it as [WIP]

**Comment by vrutkovs** [comment]
Ported to use ```osbs.http```, however my test setup doesn't let me authenticate to generate jsons

**Comment by TomasTomecek** [comment]
Try to disable auth in openshift: https://github.com/projectatomic/osbs-client/blob/master/docs/development-setup.md#building-images that could help; if not, please post some logs

**Comment by vrutkovs** [comment]
so close ...
Now I get
```
https://10.3.9.133:8443/oapi/v1/namespaces/default/builds/atomic-reactor-dockerfile-test-master-1
Traceback (most recent call last):
  File "mock_jsons.py", line 105, in <module>
    request_and_save_output_to(url, "build_put", request_type="put", use_json=True, data=build_data)
  File "mock_jsons.py", line 56, in request_and_save_output_to
    }[request_type](url, headers=headers, data=data, **request_options)
  File "build/bdist.linux-x86_64/egg/osbs/http.py", line 111, in put
  File "build/bdist.linux-x86_64/egg/osbs/http.py", line 118, in request
  File "build/bdist.linux-x86_64/egg/osbs/http.py", line 213, in __init__
TypeError: invalid arguments to setopt
Exception pycurl.error: 'curl object not on this multi-stack' in <bound method HttpStream.__del__ of <osbs.http.HttpStream object at 0x7f7682065c50>> ignored
```
on PUTting data back to the build endpoint

**Comment by twaugh** [comment]
@lcarva, not sure if you saw this.

**Comment by vrutkovs** [comment]
This PR has been hanging up for a year and its outdated. osbs-client how has `--capture` switch, so new mocks should be captured using it.

Closing this in favor of a better PR

**Pull request closed without merging**
