### PR TITLE
Use watch API to wait for autoinstantiated builds

### LINKED ISSUE #216: BuildConfig instantiation polling not quite right
For BuildConfigs we expect to instantiate builds automatically we're currently waiting up to 60 seconds for *running* builds, but we have no guarantee the builds will get scheduled in that time. All we need to wait for is *a* build to show up.

Additionally, we shouldn't really need to poll for this, just `watch` (like `OpenShift.wait()` does).

(Aside: I've been trying tests with a trigger listed in the JSON, and trying to work out how to automate tests for this.)

### PR DESCRIPTION
**Pull request by mmilata**
Closes #216.

There's no timeout, we don't have it for any other watch methods either - should we?

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Polling had 60 seconds, that sounds reasonable. Not sure about implementation, does pycurl support timeout? (or do we have to start new thread with timer?)

**Comment by mmilata** [comment]
The last time I tested this the 60 seconds were sometimes not enough. PyCURL seems to [support timeouts](http://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html). Should I open a separate ticket for this?

**Comment by TomasTomecek** [comment]
I would stuff it into this one. But to be honest, I'm not sure we need the timeout (the build should be scheduled no matter what, right?). @twaugh Tim, what do you think?

**Comment by twaugh** [comment]
I don't think it requires a timeout really.

**Comment by twaugh** [comment]
LGTM, and it works fine here.

**Comment by twaugh** [comment]
Also FWIW it took 117s for a build to get scheduled here just now.

**Comment by TomasTomecek** [comment]
> 117s for a build to get scheduled here just now.

oh my, `+1` for not doing timeout then

**Pull request merged**
