### PR TITLE
New API method import_image()

### PR DESCRIPTION
**Pull request by twaugh**
This new API method tells OpenShift to fetch new ImageStream tags for a repo being tracked in an external registry.

### CODE REVIEW

**Comment by twaugh** [comment]
This will be used by atomic-reactor to trigger layered image rebuilds when using an external Docker image repository.

**Comment by mmilata** [comment]
LGTM, is there an easy way to test it?

**Comment by twaugh** [comment]
Found a bug :-) and rebased to master.

To test it:
```
cat <<"EOF" | oc create -f -
{
  "kind":"ImageStream",
  "apiVersion":"v1",
  "metadata":{
    "name":"fedora"
  },
  "spec":{
    "dockerImageRepository":"docker.io/library/fedora"
  }
}
EOF
```

After running `osbs --conf ... import-image fedora` you should see the `openshift.io/image.dockerRepositoryCheck` timestamp refresh.

I'd love to add this to the automated testing but I'm not sure I understand how to do it. :-/

**Comment by mmilata** [comment]
Thanks, seems to work fine -> merging. Feel free to ping me on IRC regarding the tests.

**Pull request merged**
