### PR TITLE
Fix flatpak build check in bump_release renderer

### PR DESCRIPTION
**Pull request by lcarva**
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

### CODE REVIEW

**Comment by lcarva** [comment]
cc @owtaylor

**Comment by twaugh** [comment]
Does this need a tests fix?

**Comment by lcarva** [comment]
> Does this need a tests fix?

Probably. It should've been caught by unit tests. I'll add one.

**Comment by lcarva** [comment]
Unit tests updated.

**Comment by vrutkovs** [comment]
@osbs-bot's issue is resolved in https://github.com/projectatomic/atomic-reactor/pull/832

**Comment by lcarva** [comment]
Not updating release notes draft because this is bugfix to an unreleased feature.

**Pull request merged**
