### PR TITLE
Use our logging for pycurl messages

### PR DESCRIPTION
**Pull request by pbabinca**
Function is used only if self.verbose is enabled. Debug messages are
prefixed in similar way how curl's TRACE_PLAIN.

### CODE REVIEW

**Comment by pbabinca** [comment]
Proposed implementation prints logs like this:
```
2015-05-27 13:02:06,829 - osbs.http - DEBUG - pycurl *: 'About to connect() to 10.3.14.233 port 8443 (#0)
'
2015-05-27 13:02:06,829 - osbs.http - DEBUG - pycurl *: '  Trying 10.3.14.233...
'
2015-05-27 13:02:06,829 - osbs.http - DEBUG - pycurl *: 'Adding handle: conn: 0x1128a30
'
2015-05-27 13:02:06,829 - osbs.http - DEBUG - pycurl *: 'Adding handle: send: 0
'
2015-05-27 13:02:06,829 - osbs.http - DEBUG - pycurl *: 'Adding handle: recv: 0
'
2015-05-27 13:02:06,829 - osbs.http - DEBUG - pycurl *: 'Curl_addHandleToPipeline: length: 1
'
2015-05-27 13:02:06,830 - osbs.http - DEBUG - pycurl *: '- Conn 0 (0x1128a30) send_pipe: 1, recv_pipe: 0
'
2015-05-27 13:02:06,997 - osbs.http - DEBUG - pycurl *: 'Connected to 10.3.14.233 (10.3.14.233) port 8443 (#0)
'
2015-05-27 13:02:06,997 - osbs.http - DEBUG - pycurl *: 'Initializing NSS with certpath: sql:/etc/pki/nssdb
'
2015-05-27 13:02:07,272 - osbs.http - DEBUG - pycurl *: 'skipping SSL peer certificate verification
'
2015-05-27 13:02:07,298 - osbs.http - DEBUG - pycurl *: 'NSS: client certificate not found (nickname not specified)
'
2015-05-27 13:02:07,494 - osbs.http - DEBUG - pycurl *: 'SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
'
2015-05-27 13:02:07,494 - osbs.http - DEBUG - pycurl *: 'Server certificate:
'
2015-05-27 13:02:07,495 - osbs.http - DEBUG - pycurl *: '	subject: CN=127.0.0.1
'
2015-05-27 13:02:07,495 - osbs.http - DEBUG - pycurl *: '	start date: May 25 14:13:23 2015 GMT
'
2015-05-27 13:02:07,496 - osbs.http - DEBUG - pycurl *: '	expire date: May 24 14:13:24 2016 GMT
'
2015-05-27 13:02:07,496 - osbs.http - DEBUG - pycurl *: '	common name: 127.0.0.1
'
2015-05-27 13:02:07,496 - osbs.http - DEBUG - pycurl *: '	issuer: CN=openshift-signer@1432563201
'
2015-05-27 13:02:07,497 - osbs.http - DEBUG - pycurl >: 'GET /osapi/v1beta1/builds/foo:20150527105546/?namespace=default HTTP/1.1
User-Agent: PycURL/7.19.5.1 libcurl/7.32.0 NSS/3.18 Basic ECC zlib/1.2.8 libidn/1.28 libssh2/1.5.0
Host: 10.3.14.233:8443
Accept: */*

'
2015-05-27 13:02:07,829 - osbs.http - DEBUG - pycurl <: 'HTTP/1.1 404 Not Found
'
2015-05-27 13:02:07,830 - osbs.http - DEBUG - pycurl <: 'Content-Type: application/json
'
2015-05-27 13:02:07,830 - osbs.http - DEBUG - pycurl <: 'Date: Wed, 27 May 2015 11:02:06 GMT
'
2015-05-27 13:02:07,830 - osbs.http - DEBUG - pycurl <: 'Content-Length: 297
'
2015-05-27 13:02:07,831 - osbs.http - DEBUG - pycurl <: '
'
2015-05-27 13:02:07,831 - osbs.http - DEBUG - pycurl {: '{
```

I have alternative implementation which strips new lines by default and prints special header if new line wasn't found. curl doesn't add newlines if e.g. http body is split into chunks.

**Comment by TomasTomecek** [comment]
neat, let me try

**Comment by TomasTomecek** [comment]
I would prefer getting rid of the newlines, it's pretty annoying

**Comment by pbabinca** [comment]
Stripping new lines pushed. The log now looks like this:
```
2015-05-28 11:11:51,584 - osbs - DEBUG - Logging level set to debug
2015-05-28 11:11:51,585 - osbs.http - DEBUG - pycurl *: 'About to connect() to 10.3.14.233 port 8443 (#0)'
2015-05-28 11:11:51,585 - osbs.http - DEBUG - pycurl *: '  Trying 10.3.14.233...'
2015-05-28 11:11:51,586 - osbs.http - DEBUG - pycurl *: 'Adding handle: conn: 0x292f4d0'
2015-05-28 11:11:51,586 - osbs.http - DEBUG - pycurl *: 'Adding handle: send: 0'
2015-05-28 11:11:51,586 - osbs.http - DEBUG - pycurl *: 'Adding handle: recv: 0'
2015-05-28 11:11:51,586 - osbs.http - DEBUG - pycurl *: 'Curl_addHandleToPipeline: length: 1'
2015-05-28 11:11:51,586 - osbs.http - DEBUG - pycurl *: '- Conn 0 (0x292f4d0) send_pipe: 1, recv_pipe: 0'
2015-05-28 11:11:51,852 - osbs.http - DEBUG - pycurl *: 'Connected to 10.3.14.233 (10.3.14.233) port 8443 (#0)'
2015-05-28 11:11:51,852 - osbs.http - DEBUG - pycurl *: 'Initializing NSS with certpath: sql:/etc/pki/nssdb'
2015-05-28 11:11:52,270 - osbs.http - DEBUG - pycurl *: 'skipping SSL peer certificate verification'
2015-05-28 11:11:52,316 - osbs.http - DEBUG - pycurl *: 'NSS: client certificate not found (nickname not specified)'
2015-05-28 11:11:52,507 - osbs.http - DEBUG - pycurl *: 'SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA'
2015-05-28 11:11:52,507 - osbs.http - DEBUG - pycurl *: 'Server certificate:'
2015-05-28 11:11:52,507 - osbs.http - DEBUG - pycurl *: '	subject: CN=127.0.0.1'
2015-05-28 11:11:52,507 - osbs.http - DEBUG - pycurl *: '	start date: May 25 14:13:23 2015 GMT'
2015-05-28 11:11:52,507 - osbs.http - DEBUG - pycurl *: '	expire date: May 24 14:13:24 2016 GMT'
2015-05-28 11:11:52,507 - osbs.http - DEBUG - pycurl *: '	common name: 127.0.0.1'
2015-05-28 11:11:52,508 - osbs.http - DEBUG - pycurl *: '	issuer: CN=openshift-signer@1432563201'
2015-05-28 11:11:52,508 - osbs.http - DEBUG - pycurl >: 'GET /osapi/v1beta1/builds/foo-20150528-084000/?namespace=default HTTP/1.1
User-Agent: PycURL/7.19.5.1 libcurl/7.32.0 NSS/3.18 Basic ECC zlib/1.2.8 libidn/1.28 libssh2/1.5.0
Host: 10.3.14.233:8443
Accept: */*
'
'015-05-28 11:11:52,814 - osbs.http - DEBUG - pycurl <: 'HTTP/1.1 200 OK
'015-05-28 11:11:52,815 - osbs.http - DEBUG - pycurl <: 'Content-Type: application/json
'015-05-28 11:11:52,815 - osbs.http - DEBUG - pycurl <: 'Date: Thu, 28 May 2015 09:11:51 GMT
'015-05-28 11:11:52,815 - osbs.http - DEBUG - pycurl <: 'Transfer-Encoding: chunked
'015-05-28 11:11:52,816 - osbs.http - DEBUG - pycurl <: '
2015-05-28 11:11:52,816 - osbs.http - DEBUG - pycurl { !\n: '41bb
{
  "kind": "Build",
  "apiVersion": "v1beta1",
  "metadata": {
```
[snip]

Last log message was cut in this output because it is unnecessary long. But you can also see that `!\n` mark which means that the log message didn't have new line at the end.

**Comment by TomasTomecek** [comment]
I really like this idea and would like to merge it at some point. Unfortunately for me it's still pretty much unusable:
```
2015-06-03 08:36:04,698 - dock.util - DEBUG - Running transaction check
'
2015-06-03 08:36:04,698 - dock.util - DEBUG - Running transaction check
2015-06-03 14:36:06,285 - osbs.http - DEBUG - pycurl {: '47
2015-06-03 08:36:05,126 - dock.util - DEBUG - Running transaction test
'
2015-06-03 08:36:05,126 - dock.util - DEBUG - Running transaction test
2015-06-03 14:36:07,394 - osbs.http - DEBUG - pycurl {: '49
2015-06-03 08:36:06,225 - dock.util - DEBUG - Transaction test succeeded
'
2015-06-03 08:36:06,225 - dock.util - DEBUG - Transaction test succeeded
2015-06-03 14:36:07,395 - osbs.http - DEBUG - pycurl {: '42
2015-06-03 08:36:06,229 - dock.util - DEBUG - Running transaction
'
2015-06-03 08:36:06,229 - dock.util - DEBUG - Running transaction
```

**Comment by TomasTomecek** [comment]
If you do
```
logger.debug("pycurl %s%s: '%s'", debug_type, not_stripped, repr(debug_msg))
```
you'll see that whole chunks are being displayed, something like:
```
2015-06-03 14:36:07,395 - osbs.http - DEBUG - pycurl {: '42\r\n2015-06-03 08:36:06,229 - dock.util - DEBUG - Running transaction\r\n'
```

I would be probably in favor of _not_ logging any data (hardcore verbose mode maybe?) and logging just headers and curl's log messages.

**Comment by twaugh** [comment]
This feature has was included as part of #191.

**Pull request closed without merging**
