### PR TITLE
Reduce complexity in `osbs.build.build_request`

### PR DESCRIPTION
**Pull request by twaugh**
The `build_request.py` module has some pretty large `render()` methods. This pull requests breaks them up into manageable chunks so the overall process is easier to read and understand.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
This is very nice! (and also hard to review -- I vote for merging if tests pass)

**Comment by twaugh** [comment]
What I've done is move plugin-specific configuration out into separate methods with names including the plugin they are for, as well as moving out other related config updates such as resource limits.

This means the main `render()` method becomes much easier to read, as you can see very quickly which plugins are configured, and how that relates to other config changes.

I'll re-based it.

**Comment by mmilata** [comment]
Nice, merged!

**Comment by twaugh** [comment]
Thanks!

**Comment by TomasTomecek** [comment]
> What I've done is move plugin-specific configuration out into separate methods

Very well done. This was totally needed.

**Pull request merged**
