### PR TITLE
Don't crash while checking for labels in inexisting buildconfig

### PR DESCRIPTION
**Pull request by vrutkovs**
Reproduced on scratchbuild server

### CODE REVIEW

**Comment by twaugh** [comment]
This looks like the wrong fix. `build_config` at that point is one we just rendered, so it ought to have those labels set.

**Comment by vrutkovs** [comment]
Right, the title is wrong - on scratch server we always create a new buildconfig - and ```_create_build_config_and_build``` takes build config from build request

**Comment by mmilata** [comment]
The simple build also checks for existing buildconfig if i'm reading the code correctly. I've created PR #435 that attempts to fix this by adding the labels for simple builds as well.

I'm working on removing the build types entirely (#129) but not sure when it's going to be ready, would be nice if simple builds worked in the meantime.

**Comment by vrutkovs** [comment]
Closed as #435 is merged

**Pull request closed without merging**
