### PR TITLE
Configure tag_and_push plugin

### PR DESCRIPTION
**Pull request by mmilata**
OSBS counterpart of projectatomic/atomic-reactor#349 (issue projectatomic/atomic-reactor#348).

### CODE REVIEW

**Comment by bkabrda** [comment]
It'd be great to provide the registry from `spec.registry_uri` by explicitly adding it to `tag_and_push` `registries` argument with a special value and then replacing the special value if it's there. For example:

```
"registries": {
  "{{REGISTRY_URI}}": {"insecure": true},
  "some.other.registry": {"insecure": false}
}
```

This way user can:
- specify if the default registry should be used at all
- specify explicitly if the registry connection should be secure or not
- add more registries (IIUC the way it works now is that the code in `build_request.py` would just wipe out anything that was provided in `prod_inner`)

**Comment by twaugh** [comment]
@bkabrda Is that for configuring a v2 registry and/or a v1 registry, or a separate idea?

We'll need to think of a way of configuring a v2 registry soon, as well as a way for osbs-client to know which registries support which API version.

**Comment by bkabrda** [comment]
A separate idea, just to make configuring the plugin easier.

In term of V1/V2, I *think* we don't need to configure anything, since Docker client will first try pushing to V2 at given URI, then fallback to V1 and then fail if none is found. Therefore we just need to provide registry URIs and Docker client should do "the right thing" depending on which version of registry runs on the URI.

(I think we don't need to cover the case where both registries would be running on the same URI. I'm not sure that's even possible...)

**Comment by twaugh** [comment]
Well, we do need to configure which registries to try pushing to, because that's what the `registry_api_versions` parameter is for.

**Comment by bkabrda** [comment]
Hmm, that's right. So how about this:

```
"registries": {
  "foo": {
    "insecure": true,
    "version": 1
  },
  "bar": {
    "insecure": true,
    "version": 2
  }
}
```

Then the client would remove registries of versions that are not in `registry_api_versions`.

**Comment by twaugh** [comment]
Yes, that looks good. And the `tag_and_push` plugin can just ignore `version`.

**Comment by mmilata** [comment]
@bkabrda Updated with your suggestion.

**Comment by bkabrda** [comment]
LGTM. @twaugh are you ok with merging or do you have additional comments?

**Comment by twaugh** [comment]
LGTM

**Comment by mmilata** [comment]
Did one cosmetic change in tests, sorry.

**Comment by bkabrda** [comment]
Still LGTM, merging :+1:

**Comment by mmilata** [comment]
Thanks:)

**Pull request merged**
