### PR TITLE
Use registry_api_versions to support v1 and/or v2

### PR DESCRIPTION
**Pull request by twaugh**
Use `registry_api_versions` to adjust build config as appropriate.

### CODE REVIEW

**Comment by twaugh** [comment]
Ready for review.

**Comment by TomasTomecek** [comment]
LGTM
(I feel like we are getting to a point, where we should lose the `ini` conf and do json instead)

**Comment by twaugh** [comment]
Or YAML, yes. I would love that. The INI format is so restrictive.

**Comment by twaugh** [comment]
Re-based against master.

**Pull request merged**
