### PR TITLE
Enable tag_from_config plugin

### PR DESCRIPTION
**Pull request by lcarva**
This can be merged, but a new release would require a release of atomic-reactor containing the following changes: https://github.com/projectatomic/atomic-reactor/pull/515

### CODE REVIEW

**Comment by vrutkovs** [comment]
LGTM

**Comment by mmilata** [comment]
I think atomic-reactor won't fail when build json contains unknown plugin ... let me check.

**Comment by mmilata** [comment]
Ok, it's not the case, whole build fails when unknown plugin is encountered.

I'd wait for a-r release and then merge it. Or we can enable the plugin conditionally based on osbs.conf. Ideas?

**Comment by lcarva** [comment]
I think it's safe to merge, it's just the release that must be synchronized properly.

**Comment by vrutkovs** [comment]
Agreed, its safe to merge (just to be sure we can make an interim release of atomic-reactor)

**Comment by mmilata** [comment]
Alright, merged.

**Pull request merged**
