### PR TITLE
import_image will be as well exit plugin

### PR DESCRIPTION
**Pull request by rcerven**
Signed-off-by: Robert Cerven <rcerven@redhat.com>

### CODE REVIEW

**Comment by twaugh** [comment]
I'd like to see the commit message explain a little more why we need to run this as an exit plugin (so it runs after pulp_publish), and why we still need to handle configuring it as a post-build plugin (for 'prod' builds).

**Comment by rcerven** [comment]
Improved commit message

**Comment by lcarva** [comment]
Once merged, https://github.com/projectatomic/osbs-client/pull/730 might have to be rebased.

**Comment by rcerven** [comment]
rn updated : 
import_image is now also an ExitPlugin

**Pull request merged**
