### PR TITLE
improve `list-builds`

### PR DESCRIPTION
**Pull request by TomasTomecek**

### CODE REVIEW

**Comment by twaugh** [comment]
This looks fantastic!

**Comment by twaugh** [comment]
I like this a lot. Maybe the 'make filtering more generic' part could be more generic though: I can see it being useful to filter on particular values for particular fields.

`osbs list-builds image_id=...` would show the build that produced a given image.

`osbs list-builds user=alice user=bob` would list builds for both alice and bob (same key name so logical OR).

`osbs list-builds state=pending image=alice/image1 image=alice/image2` would list alice's pending builds for image1 and image2 (logical AND and ORs inferred like journalctl does).

What do you think?

**Comment by TomasTomecek** [comment]
Tim, thanks sounds like an awesome idea. I would prefer not to implement it in this PR b/c it looks like a lot of work and that would make this PR open forever. Can you create a new issue please?

**Comment by twaugh** [comment]
The reason I mentioned it now is that I don't want us to have to change the CLI in an incompatible way later.

I suppose it can be made compatible though: if a filter expression contains '=' then it would perform the matching I described above; otherwise it would search for a substring in the image name (i.e. it would be equivalent to adding image=... parameters for each substring that exists).

Just wanted to be clear on where we're going.

**Comment by twaugh** [comment]
Filed enhanced filtering as #252.

**Comment by TomasTomecek** [comment]
Ready for merge from my PoV.

**Comment by twaugh** [comment]
https://github.com/twaugh/osbs-client/commit/c2351a85b6de34919162be9373fd2b8387417d7e has a test to verify the output of `TablePrinter` using `capsys`.

**Comment by TomasTomecek** [comment]
@twaugh very nice!!

**Comment by twaugh** [comment]
Feel free to cherry-pick it.

**Comment by TomasTomecek** [comment]
I thought you already pushed that in this branch.

(wow, doesn't work on 3, since it looks like that python 3 division outputs floats, not ints; will fix)

**Comment by twaugh** [comment]
Looks like you need `//` instead of `/`.

**Comment by TomasTomecek** [comment]
indeed so, will use that instead

**Comment by twaugh** [comment]
LGTM

**Pull request merged**
