### PR TITLE
enable basic auth for metadata plugin

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes https://github.com/projectatomic/atomic-reactor/issues/294

### CODE REVIEW

**Comment by twaugh** [comment]
In the GitHub issue, @mmilata said:

> I'd prefer if we didn't pass the username/password to atomic-reactor - it will get stored in the build logs and build metadata (iirc).

I have a suggestion for how plugins ought to authenticate: they can use the service account's token.
https://docs.openshift.org/latest/dev_guide/service_accounts.html#using-a-service-account-s-credentials-inside-a-container

**Comment by mmilata** [comment]
@twaugh :+1: This way we can also get rid of the auth proxy snippet. This doesn't need the multiple secrets support that will be in 1.0.6, right?

**Comment by twaugh** [comment]
No, it's independent of that.

**Comment by twaugh** [comment]
I've filed #237 to track it.

**Comment by TomasTomecek** [comment]
Sounds good, let's close this then.

**Pull request closed without merging**
