### PR TITLE
cli,help: get rid of 'u' prefix in help

### PR DESCRIPTION
**Pull request by TomasTomecek**
```
main.py: error: invalid choice: 'asd' (choose from u'list-builds', u'watch-build', u'get-build', u'cancel-build', u'import-image', u'get-token', u'get-user', u'build-logs', u'build')
```

### CODE REVIEW

**Comment by mmilata** [comment]
Now it prints following when using python3 :(
```
...
            [--namespace NAMESPACE]
            {b'list-builds',b'watch-build',b'get-build',b'cancel-build',b'import-image',b'get-token',b'get-user',b'build-logs',b'build'}
            ...
osbs: error: invalid choice: 'what' (choose from b'list-builds', b'watch-build', b'get-build', b'cancel-build', b'import-image', b'get-token', b'get-user', b'build-logs', b'build')

```

**Comment by TomasTomecek** [comment]
@_@

okay, am going to try harder

**Comment by TomasTomecek** [comment]
my hatred level raises

hope this will do (ready for review)

**Comment by mmilata** [comment]
Works fine, merged!

**Pull request merged**
