### PR TITLE
don't run import_image for scratch build

### PR DESCRIPTION
**Pull request by rcerven**
Signed-off-by: Robert Cerven <rcerven@redhat.com>

### CODE REVIEW

**Comment by vrutkovs** [comment]
Wouldn't it be more explicit to update `def adjust_for_scratch` instead?

**Comment by rcerven** [comment]
right will do that, thanks

**Comment by vrutkovs** [comment]
>ahh I can't do that, adjust_for_scratch is running before render_import_image

That's exactly the point of this change - remove the plugin as early as possible

**Comment by rcerven** [comment]
ok I was looking wrong, will remove it in adjust_for_scratch

**Pull request merged**
