### PR TITLE
Update CONTRIBUTING.md to refer to the review checklist

### PR DESCRIPTION
**Pull request by twaugh**
Signed-off-by: Tim Waugh <twaugh@redhat.com>

### CODE REVIEW

**Comment by twaugh** [comment]
I think getpip broke again.

**Comment by lcarva** [comment]
Please rebase to pick up unit test fix.

**Comment by twaugh** [comment]
Updated.

**Comment by lcarva** [comment]
Not updating release notes draft because this is a change solely to docs.

**Pull request merged**
