### PR TITLE
Check that at least one registry is provided

### LINKED ISSUE #268: validate registry_uri.value
```
Original traceback (most recent call last):
  File "osbs-client/osbs/api.py", line 33, in catch_exceptions
    return func(*args, **kwargs)
  File "osbs-client/osbs/api.py", line 285, in create_prod_build
    git_push_username=self.build_conf.get_git_push_username(),
  File "osbs-client/osbs/build/build_request.py", line 264, in set_params
    self.spec.set_params(**kwargs)
  File "osbs-client/osbs/build/spec.py", line 236, in set_params
    name_label)
  File "/usr/lib64/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError("'NoneType' object has no attribute 'endswith'",)

```

### PR DESCRIPTION
**Pull request by mmilata**
Closes #268.

### CODE REVIEW

**Comment by twaugh** [comment]
Does this make sense for v1 though? In the v1 workflow we don't use the registry when pulp is in use do we?

**Comment by mmilata** [comment]
Good point. It seems we always use it (even if a-r won't push there): https://github.com/projectatomic/osbs-client/blob/master/osbs/build/build_request.py#L257

I'll check if OpenShift can handle having no output registry, then we can set it only if there's at least one registry provided.

**Comment by mmilata** [comment]
Never mind, we already do that when using pulp. I'll fix the PR ...

**Comment by mmilata** [comment]
Updated.

**Comment by twaugh** [comment]
Should we test it too?

**Comment by mmilata** [comment]
Added test and rebased.

**Comment by twaugh** [comment]
LGTM

**Pull request merged**
