### PR TITLE
watch_resource: reconnect when connection closed (#339)

### PR DESCRIPTION
**Pull request by twaugh**
To test: pause a builder and submit a job, then wait for an hour.

### CODE REVIEW

**Comment by twaugh** [comment]
Tested against Origin 1.0.8. Fixes #339.

**Comment by mmilata** [comment]
LGTM, merged!

**Comment by mmilata** [comment]
Thinking about it, shouldn't we have a short sleep between the retries, or perhaps a limited number of retries?

**Comment by twaugh** [comment]
Hmm, yes.

**Pull request merged**
