### PR TITLE
Reject URIs as values of registry_uri

### PR DESCRIPTION
**Pull request by mmilata**
The name is confusing:/

### CODE REVIEW

**Comment by twaugh** [comment]
Maybe we could just drop the scheme part altogether? e.g. https://github.com/projectatomic/atomic-reactor/commit/53cc20e0570a030dd15031bd43758c7aca8e0283

**Comment by mmilata** [comment]
Good idea - I'll update the PR.

**Comment by mmilata** [comment]
Updated.

**Comment by twaugh** [comment]
@mmilata Mind if I add a test case?

**Comment by twaugh** [comment]
LGTM

**Comment by mmilata** [comment]
Thanks! Feel free to not merge until I add a test case next time;)

**Pull request merged**
