### PR TITLE
Remove support for OpenShift v1.0.5 and below

### PR DESCRIPTION
**Pull request by lcarva**

### CODE REVIEW

**Comment by twaugh** [comment]
How about docs/secret.md?

**Comment by lcarva** [comment]
Updated docs/secret.md

**Comment by twaugh** [comment]
How about `tests/mock_jsons/0.5.4`?

**Comment by lcarva** [comment]
I think ideally, we want to regenerate those jsons (0.5.4 and 1.0.4) for newer versions (1.0.6 and 1.3.3).
I went down this road by running `mock_jsons.sh` which had to be modified slightly, but it only produces some of the files needed.
I can address those, but it'll make this patch, and story, much larger. Wasn't sure if we wanted to focus mainly on doc and code updates for now.

**Comment by twaugh** [comment]
Fair enough.

**Pull request merged**
